const mediaItems: MediaItem[] = [
  {
    id: 10,
    type: "image",
    title: "image",
    description: "image",
    src: "/portfolio/webp/image10.webp",
    alt: "image10.webp",
    height: 1080,
    width: 1920,
  },
  {
    id: 11,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image11.webp",
    alt: "image11.webp",
    height: 1080,
    width: 1900,
  },
  {
    id: 12,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image12.webp",
    alt: "image12.webp",
    height: 1080,
    width: 1080,
  },
  {
    id: 13,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image13.webp",
    alt: "image13.webp",
    height: 1080,
    width: 1920,
  },
  {
    id: 14,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image14.webp",
    alt: "image14.webp",
    height: 1080,
    width: 1080,
  },
  {
    id: 15,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image15.webp",
    alt: "image15.webp",
    height: 1080,
    width: 1080,
  },
  {
    id: 16,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image16.webp",
    alt: "image16.webp",
    height: 1080,
    width: 1920,
  },
  {
    id: 17,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image17.webp",
    alt: "image17.webp",
    height: 1080,
    width: 1920,
  },
  {
    id: 18,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image18.webp",
    alt: "image18.webp",
    height: 1080,
    width: 1920,
  },
  {
    id: 19,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image19.webp",
    alt: "image19.webp",
    height: 1080,
    width: 1080,
  },
  {
    id: 1,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image1.webp",
    alt: "image1.webp",
    height: 1080,
    width: 1920,
  },
  {
    id: 20,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image20.webp",
    alt: "image20.webp",
    height: 1080,
    width: 1920,
  },
  {
    id: 2,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image2.webp",
    alt: "image2.webp",
    height: 1080,
    width: 864,
  },
  {
    id: 3,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image3.webp",
    alt: "image3.webp",
    height: 1080,
    width: 1920,
  },
  {
    id: 4,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image4.webp",
    alt: "image4.webp",
    height: 1080,
    width: 1920,
  },
  {
    id: 5,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image5.webp",
    alt: "image5.webp",
    height: 1080,
    width: 835,
  },
  {
    id: 6,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image6.webp",
    alt: "image6.webp",
    height: 1080,
    width: 1080,
  },
  {
    id: 7,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image7.webp",
    alt: "image7.webp",
    height: 1080,
    width: 1920,
  },
  {
    id: 8,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image8.webp",
    alt: "image8.webp",
    height: 1080,
    width: 1920,
  },
  {
    id: 9,
    description: "image",
    type: "image",
    title: "image",
    src: "/portfolio/webp/image9.webp",
    alt: "image9.webp",
    height: 1080,
    width: 1920,
  },
  {
    id: 10002,
    description: "video",
    type: "video",
    title: "video",
    src: "/portfolio/webm/gif2.webm",
    alt: "gif2.webm",
    height: 600,
    width: 600,
  },
  {
    id: 10003,
    description: "video",
    type: "video",
    title: "image",
    src: "/portfolio/webm/gif3.webm",
    alt: "gif3.webm",
    height: 600,
    width: 600,
  },
  {
    id: 10004,
    description: "video",
    type: "video",
    title: "image",
    src: "/portfolio/webm/gif4.webm",
    alt: "gif4.webm",
    height: 600,
    width: 600,
  },
  {
    id: 10005,
    description: "video",
    type: "video",
    title: "image",
    src: "/portfolio/webm/gif5.webm",
    alt: "gif5.webm",
    height: 600,
    width: 600,
  },
  {
    id: 10006,
    description: "video",
    type: "video",
    title: "image",
    src: "/portfolio/webm/gif6.webm",
    alt: "gif6.webm",
    height: 600,
    width: 600,
  },
  {
    id: 10007,
    description: "video",
    type: "video",
    title: "image",
    src: "/portfolio/webm/gif7.webm",
    alt: "gif7.webm",
    height: 600,
    width: 600,
  },
  {
    id: 10008,
    description:
      "[Typescript, Vite, React] A GPT AI Journaling Companion that aimed to give you insight and more hindsight on what you wrote. It would generally ask questions about things you'd mention, was a tad bit over-optimistic!",
    type: "text",
    title: "Second Sight",
    src: "https://github.com/progresssh/second-sight",
    alt: "Second Sight",
    height: 0,
    width: 0,
  },
];

export default mediaItems;
